FROM node:20-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund
COPY . .
ARG TARO_APP_AUTH_SERVICE_URL
ENV TARO_APP_AUTH_SERVICE_URL=${TARO_APP_AUTH_SERVICE_URL}
ARG TARO_APP_GAME_SERVICE_URL
ENV TARO_APP_GAME_SERVICE_URL=${TARO_APP_GAME_SERVICE_URL}
ARG TARO_APP_SOCIAL_SERVICE_URL
ENV TARO_APP_SOCIAL_SERVICE_URL=${TARO_APP_SOCIAL_SERVICE_URL}
ARG TARO_APP_FEED_SERVICE_URL
ENV TARO_APP_FEED_SERVICE_URL=${TARO_APP_FEED_SERVICE_URL}
ARG TARO_APP_AI_SERVICE_URL
ENV TARO_APP_AI_SERVICE_URL=${TARO_APP_AI_SERVICE_URL}
ARG TARO_APP_WS_URL
ENV TARO_APP_WS_URL=${TARO_APP_WS_URL}
ARG TARO_APP_GAME_CONTENT_URL
ENV TARO_APP_GAME_CONTENT_URL=${TARO_APP_GAME_CONTENT_URL}
ARG TARO_APP_GAME_SHELL_URL
ENV TARO_APP_GAME_SHELL_URL=${TARO_APP_GAME_SHELL_URL}
ARG TARO_APP_ENABLE_WECHAT_H5_LOGIN
ENV TARO_APP_ENABLE_WECHAT_H5_LOGIN=${TARO_APP_ENABLE_WECHAT_H5_LOGIN}
ARG TARO_APP_WECHAT_OAUTH_APP_ID
ENV TARO_APP_WECHAT_OAUTH_APP_ID=${TARO_APP_WECHAT_OAUTH_APP_ID}
ARG TARO_APP_WECHAT_OAUTH_SCOPE
ENV TARO_APP_WECHAT_OAUTH_SCOPE=${TARO_APP_WECHAT_OAUTH_SCOPE}
RUN npm run build:h5
FROM nginx:stable-alpine
COPY --from=build /app/dist/h5 /usr/share/nginx/html
COPY 33zqDBay4T.txt /usr/share/nginx/html/33zqDBay4T.txt
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
